### ISSUE TITLE
Chose board to flash by port

### ISSUE THREAD

**Issue by VincentR1** [Infineon/XMC-for-Arduino#209]
**Is your feature request related to a problem? Please describe.**
I work on a sensor using prox 30 single hall sensors which are on single Infineon:arm:XMC1100_XMC2GO".
For updating the sensor i wrote a script which should targets one board after another iterating over the ports using the adurino cli.

arduino-cli upload -p /dev/ttyACM1 -b Infineon:arm:XMC1100_XMC2GO`

-> which leeds to:
java -jar "~/.arduino15/packages/Infineon/tools/XMCFlasher/1.2.1/XMCFlasher.jar" -p "/tmp/arduino-sketch-47D7AF5586EB509566B17F69DFB282A0/HallSensor.ino.hex"  -device "XMC1100-0064"

The board is updated.  the problem is its updating the first board 30 times the other ones are not.
Is there a way to specifiy the port using the xmc flasher directly?

I have to un plug all sensors first and then replug and update each sensor one by one

**Describe the solution you'd like**
a way to specify the port to the board 
java -jar "~/.arduino15/packages/Infineon/tools/XMCFlasher/1.2.1/XMCFlasher.jar" -p "/tmp/arduino-sketch-47D7AF5586EB509566B17F69DFB282A0/HallSensor.ino.hex"  -device "XMC1100-0064" -port "/dev/ttyACM1"

the board on port "/dev/ttyACM1" is updated

**Comment by jaenrig-ifx** [comment]
Hi @VincentR1,

I am not sure if the XMCFlasher has such option...
But this software is sitting on top of SEGGER JLink which offers some ways to do this directly. You can create a bash script which builds your binary using the arduino-cli and later flash using JFlash (instead of the arduino-cli upload option) which allows parallel programming multiple targets.
Check the section 5.4 Programming multiple targets in parallel of this [manual](https://www.segger.com/downloads/jlink/UM08003)
