### ISSUE TITLE
Multiple definition of CCU40_0_IRQHandler

### ISSUE THREAD

**Issue by biofiction** [Infineon/XMC-for-Arduino#211]
CCU40_0_IRQHandler() is defined multiple times.

when using the <DeviceControlXMC.h>
and
attachInterrupt(digitalPinToInterrupt(9), alarmMatch, RISING);
 causes a error message

C:\Users\cguen\AppData\Local\Temp\arduino_build_359578/..\arduino_cache_705162\core\core_Infineon_arm_XMC1100_H_BRIDGE2GO_UART_debug,LIB_NONE_1ca69f617a43b0e49b5c85f4dd74c788.a(WInterrupts.c.o): In function `CCU40_0_IRQHandler':
C:\Users\cguen\AppData\Local\Arduino15\packages\Infineon\hardware\arm\1.6.0\cores/WInterrupts.c:55: multiple definition of `CCU40_0_IRQHandler'
libraries\DeviceControlXMC\utility\timer.c.o:C:\Users\cguen\AppData\Local\Arduino15\packages\Infineon\hardware\arm\1.6.0\libraries\DeviceControlXMC\src\utility/timer.c:66: first defined here

I have removed the implementation in timer.c this has fixed the issue

**Comment by boramonideep** [comment]
Hello @biofiction 

Most of the XMC boards use the CCU4 input channels to generate service requests and use them as interrupts except a few, which use the ERU for interrupts. For example: XMC4200 P2GO. The CCU4 instance 0 is generally used so the IRQ handler is `CCU4_0_IRQHandler()`. 

The examples in the library `DeviceControlXMC` also uses the CCU40 slice 0 for timer related functions. On timer overflow, the `CCU4_0_IRQHandler()` is then triggered. 

Since these two applications are overlapping in your code, the given error occurs. If you do not wish to utilize the timer-related functions in your applications, commenting out or removing the `CCU40_IRQHandler()` is an acceptable option. If however, you would want use the timer-related functions, then you must use a board which does not use the CCU4 for interrupt generation, as mentioned above. Another way would be to use an interrupt at another location/pin.

A suggestion from our side is to generally use the newer releases of XMC-for-Arduino (>1.7) as they are more stable.
