### ISSUE TITLE
Problem with examples

### ISSUE THREAD

**Issue by j0412** [Infineon/XMC-for-Arduino#50]
I tried to compile several examples but they don't work. I am using the Arduino IDE version 1.8.5 and  XMC 4700 board. Examples not compiling are: BGT24LTR11/print_motion, BGT24LTR11/print_raw_data, IFX9201 H-Bridge/MotorControl, RTC/HibernateRTC, SPI/BarometricPressureSensor, SPI/DigitalPotControl, Wire/digital_potentiometer, Wire/master_reader, Wire/master_writer, Wire/SFRRanger_reader, Wire/slave_receiver, Wire/slave_sender.
For example: in example HibernateRTC there is just no XMC_DeviceControl.h directory.

**Comment by techpaul** [comment]
In Devcecontrol examples there appears to have been some file naming mix up as far as I can see (as a user scanning code)

DieTemperatureMeasurement example, which compiles uses

      #include <DeviceControlXMC.h>

Where as HibernateRTCAlarm example uses

     #include <XMC_DeviceControl.h>

Try changinging that line to the one above that, which worked for me getting compile to work.

The other issues not had time to look apart there appears to be a missing include file and its call, many items referenced but not defined anywhere I can see yet brieflky. When I get time I can see if I can hunt down a few things, I am sure Manuel will also look for what is missing.

**Comment by techpaul** [comment]
There are some other issues I will look at over time as well which are not as pressing as your current needs

**Comment by techpaul** [comment]
Further test from Searches appears BGT24LTR11 examples only work with XMC1300 Sense2Go

**Comment by j0412** [comment]
Thank you very much!!

**Comment by techpaul** [comment]
When I get some time I will look at the other examples might not be today though as I have some other paying jobs to deal; with.

**Comment by techpaul** [comment]
Quick scxan some of the issues are related to specific boards that examples only work with certain boards (as that is the only boards they are configured for) I will see if we can add some meaningful errors to warn people they only work with one board or a few boards.

**Comment by mhollfelder** [comment]
Thank you very much for reporting these issues.

@techpaul: thank you very much for analyzing this issue and providing help here!

The problem is (as Paul said) that not all boards can be combined with all examples, e.g. the library for the BGT24LTR11 is only for the Sense2GoL, we forgot to implement a proper check here.
However, other issues are related to the fact that some parts have been changed merging for the new release and we forgot to adapt everything.
I assume that there are some issues which I need to fix right now.

Currently, I am preparing all the documentation and we are changing the documentation in the source code to make this clear as well. As promised, we will also change the wiki and include more documentation for this repository.

I will fix these issues and push them to the develop branch as soon as possible.
Sorry for any inconvenience caused by these issues.

Best regards,

Manuel

**Comment by techpaul** [comment]
Some of the DeviceControl and other examples have had updates and are available by copying files from the develop branch at the moment.

**Comment by mhollfelder** [comment]
Indeed, Paul has improved a lot here and we are catching up for a new release.
We are testing everything right now, but we expect a new release fixing the mentioned issues as well as bringing new improvements by next week.

If someone needs help, please do not hesitate to open a specific issue or contact us directly.

Best,

Manuel

**Comment by techpaul** [comment]
V1.1.2 relase has many fixes in for the examples now
