### ISSUE TITLE
i2c issues on XMC2GO

### ISSUE THREAD

**Issue by PabloPL** [Infineon/XMC-for-Arduino#64]
I've connected ssd1306 oled display over i2c to xmc2go.

I've tried to run program from https://playground.arduino.cc/Main/I2cScanner, but it's reporting that there is device connected over i2c, at (almost) every possible address

```
Scanning...
I2C device found at address 0x01  !
I2C device found at address 0x08  !
I2C device found at address 0x10  !
I2C device found at address 0x19  !
I2C device found at address 0x1F  !
I2C device found at address 0x29  !
I2C device found at address 0x2E  !
I2C device found at address 0x37  !
I2C device found at address 0x3C  !
I2C device found at address 0x44  !
I2C device found at address 0x48  !
I2C device found at address 0x50  !
I2C device found at address 0x53  !
I2C device found at address 0x5A  !
I2C device found at address 0x64  !
I2C device found at address 0x6E  !
```

After adding Wire.write(1) in loop, so it looks like

```
Wire.beginTransmission(address);
Wire.write(1);
error = Wire.endTransmission();
```

It works fine

```
Scanning...
I2C device found at address 0x3C  !
done
```

Second issue is that when I've conected ssd1306 display over i2c do xmc2go, with following code 
https://gist.github.com/PabloPL/606615c00ef39bfd6b00c42a4db17ddb 
(needs https://github.com/adafruit/Adafruit-GFX-Library and https://github.com/adafruit/Adafruit_SSD1306) it's running fine till reset/power down of board.
After power down and power up, app is blinkin leds correctly (so it's running), but lcd is not displaying anything.
I need to flash again this code to device and then it's working fine (till next power down/reset).

I'm using platform.io with https://github.com/Infineon/platformio-infineonxmc

**Comment by techpaul** [comment]
This is based on many years of experience with I2C from bit-banging toembedded controllers and designing slave devices that worked up to 1MHz inside FPGA.

First of all I have not checked the wire code yet.

Secondly that is NOT every address, see https://raspberrypi.stackexchange.com/questions/32719/i2cdetect-shows-every-possible-address for an example of a Linux I2C scanner responding to all addresses. Your output suggests another issue with the Wire code being different.

I would suggest if anything you do a scanner that works like i2cdetect see man page
https://www.systutorials.com/docs/linux/man/8-i2cdetect/

Also the person on Arduino site as usual has no idea how i2c bus works and HAPPENED to have something work for them and it is a BAD example just on address ranges as they are scanning reserved addresses for multi-master, programmeable slave addressing, High speed mdoe devices (1MHz and 3.4MHz bus clock), as well as 10 bit addressing, and other bus protocols.

See an example of restrictions at https://www.i2c-bus.org/addressing/

Set your scanner to scan addresses 8 to 119 (0x8 to 0x77).

Your issues with power cycling are likely NOTHING to do with wire code more what is being reset or not and if the SSD1306 is reset as well whilst the reset occurs in middle of an I2C transaction. Just because you have reset the micro you have NOT reset the SSD1306 until a power cycle. Probably as it is driving SDA line or doing a WAIT state holding down SCL so nothing can talk to it or send a STOP or START condition. Do you drive a signal to the RESETt pin on the SSD1306?

See https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf (section 8.5 Reset Circuit )

An initialisation guide is to actually control the I2C pins in setup to do
1. Set pins open drain write an effective 1 (high)
2  Read BOTH SDA and SCL pins ensure both high (1)
3  Toggle SCL at maximum of 100Khz rate for at least 9 clock cycle
4. Read BOTH pins check both at 1 (high) showing bus is in Idle state

You may need to extend time before first access to SSD1306 to ensure all I2C initialisation has been done and the SSD1306 has finished its initialisation. Not uncommon on character LCDs (HD44780 devices) to have to wait anything upto 500 ms before sending configuartion data.

I suspect when flashing the SSD1306 has had plenty of time to initialise itself before the programme starts, but not when power cycled/reset

**Comment by techpaul** [comment]
I have been having a brief look down into Wire.cpp, its utility xmc_i2c_conf.c and the XMCLIB xmc_i2c.c

Yes there are issues and may take me a while to resolve the many issues in the layers, assumption is at least 1 byte of data to send other replicated functions needs a tidy up massively.

**Comment by PabloPL** [comment]
@techpaul 
```
Try at start of your setup function adding

delay( 500 );
```
Ok that solved issue. Thanks ! It even works with delay(30).

Ok, so second part of this bugreport is solved (and was not a bug related to XMC).

**Comment by techpaul** [comment]
Glad that is fixed 

I am looking at tidying up the I2C levels of libraries and why randoim data gets random ACK/NACK for detecting non-existant devices, and other issues.

**Comment by mhanuel26** [comment]
Hello,

I am wondering why this issue have been closed, I haven't been able to make I2C work with XMC 2Go and 3D magnetic sensor 2Go board.
The delay workaround don't work for me, using the I2C scanner returns like a 100 devices even if there is none connected.

Could someone please let me know if this is a well known bug or something that prevent a working I2C on this boards please ?
